/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as CustomerFindRouteImport } from './routes/customer.find'
import { Route as CustomerHistoryRouteImport } from './routes/customer.history'
import { Route as CustomerNearbyRouteImport } from './routes/customer.nearby'
import { Route as CustomerNotificationsRouteImport } from './routes/customer.notifications'
import { Route as CustomerPodsPodIdRouteImport } from './routes/customer.pods.$podId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerFindRoute = CustomerFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerHistoryRoute = CustomerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerNearbyRoute = CustomerNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerPodsPodIdRoute = CustomerPodsPodIdRouteImport.update({
  id: '/pods/$podId',
  path: '/pods/$podId',
  getParentRoute: () => CustomerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/customer/find': typeof CustomerFindRoute
  '/customer/history': typeof CustomerHistoryRoute
  '/customer/nearby': typeof CustomerNearbyRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/': typeof CustomerIndexRoute
  '/customer/pods/$podId': typeof CustomerPodsPodIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer/find': typeof CustomerFindRoute
  '/customer/history': typeof CustomerHistoryRoute
  '/customer/nearby': typeof CustomerNearbyRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer': typeof CustomerIndexRoute
  '/customer/pods/$podId': typeof CustomerPodsPodIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer': typeof CustomerRouteWithChildren
  '/customer/find': typeof CustomerFindRoute
  '/customer/history': typeof CustomerHistoryRoute
  '/customer/nearby': typeof CustomerNearbyRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/': typeof CustomerIndexRoute
  '/customer/pods/$podId': typeof CustomerPodsPodIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer'
    | '/customer/find'
    | '/customer/history'
    | '/customer/nearby'
    | '/customer/notifications'
    | '/customer/'
    | '/customer/pods/$podId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer/find'
    | '/customer/history'
    | '/customer/nearby'
    | '/customer/notifications'
    | '/customer'
    | '/customer/pods/$podId'
  id:
    | '__root__'
    | '/'
    | '/customer'
    | '/customer/find'
    | '/customer/history'
    | '/customer/nearby'
    | '/customer/notifications'
    | '/customer/'
    | '/customer/pods/$podId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRoute: typeof CustomerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/find': {
      id: '/customer/find'
      path: '/find'
      fullPath: '/customer/find'
      preLoaderRoute: typeof CustomerFindRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/history': {
      id: '/customer/history'
      path: '/history'
      fullPath: '/customer/history'
      preLoaderRoute: typeof CustomerHistoryRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/nearby': {
      id: '/customer/nearby'
      path: '/nearby'
      fullPath: '/customer/nearby'
      preLoaderRoute: typeof CustomerNearbyRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/pods/$podId': {
      id: '/customer/pods/$podId'
      path: '/pods/$podId'
      fullPath: '/customer/pods/$podId'
      preLoaderRoute: typeof CustomerPodsPodIdRouteImport
      parentRoute: typeof CustomerRoute
    }
  }
}

interface CustomerRouteChildren {
  CustomerFindRoute: typeof CustomerFindRoute
  CustomerHistoryRoute: typeof CustomerHistoryRoute
  CustomerNearbyRoute: typeof CustomerNearbyRoute
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerPodsPodIdRoute: typeof CustomerPodsPodIdRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerFindRoute: CustomerFindRoute,
  CustomerHistoryRoute: CustomerHistoryRoute,
  CustomerNearbyRoute: CustomerNearbyRoute,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerPodsPodIdRoute: CustomerPodsPodIdRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRoute: CustomerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
